
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import landscape, A4

from core.rules.risk import calculate_risk_from_rules
from core.workflow.states import normalize_legacy_state
from i18n.labels import (
    canton_label,
    nationality_label,
    permit_label,
    mode_label,
    workflow_state_label
)


def export_company_summary_pdf(filename, company, cases, lang="en"):

    doc = SimpleDocTemplate(filename, pagesize=landscape(A4))
    styles = getSampleStyleSheet()
    content = []


    content.append(Paragraph(f"Company Report — {company}", styles["Title"]))
    content.append(Spacer(1, 15))


    total_cases = len(cases)
    risks = [calculate_risk_from_rules(c)[0] for c in cases]
    avg_risk = sum(risks) / len(risks) if risks else 0

    content.append(Paragraph("Overview", styles["Heading2"]))
    content.append(Paragraph(f"Total Cases: {total_cases}", styles["Normal"]))
    content.append(Paragraph(f"Average Risk: {avg_risk:.0f} / 100", styles["Normal"]))
    content.append(Spacer(1, 15))


    content.append(Paragraph("Cases", styles["Heading2"]))

    table_data = [
        ["Employee", "Nationality", "Canton", "Permit", "Mode", "Risk", "Stage"]
    ]

    for case in cases:

        risk_score, _ = calculate_risk_from_rules(case)

        table_data.append([
            case[1],
            nationality_label(case[2], lang),
            canton_label(case[3], lang),
            permit_label(case[4], lang),
            mode_label(case[5], lang),
            str(risk_score),
            workflow_state_label(normalize_legacy_state(case[8]), lang),
        ])

    table = Table(table_data, repeatRows=1)

    table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, None),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BACKGROUND", (0, 0), (-1, 0), "#dddddd"),
        ])
    )

    content.append(table)
    content.append(Spacer(1, 20))

    content.append(
        Paragraph(
            "Generated by MobilityFlow AI",
            styles["Italic"]
        )
    )

    doc.build(content)
