from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import landscape, A4


def export_case_pdf(filename, case, tasks, docs):

    doc = SimpleDocTemplate(
        filename,
        pagesize=landscape(A4)
    )

    styles = getSampleStyleSheet()

    content = []


    content.append(
        Paragraph(
            "Swiss Relocation Case File",
            styles["Title"]
        )
    )

    content.append(Spacer(1, 15))


    content.append(
        Paragraph(
            "Case Overview",
            styles["Heading2"]
        )
    )


    data = [
        [
            "Employee",
            "Nationality",
            "Canton",
            "Permit",
            "Business Mode",
            "Employer",
            "Status",
            "Risk"
        ],
        [
            case[1],
            case[2],
            case[3],
            case[4],
            case[5],
            case[6],
            case[7],
            case[9]
        ]
    ]


    table = Table(data)

    table.setStyle(
        TableStyle([
            ("GRID",(0,0),(-1,-1),0.5,None),
            ("VALIGN",(0,0),(-1,-1),"MIDDLE")
        ])
    )

    content.append(table)

    content.append(Spacer(1,15))


    content.append(
        Paragraph(
            "AI Summary",
            styles["Heading2"]
        )
    )

    content.append(
        Paragraph(
            str(case[10]).replace("\n","<br/>"),
            styles["Normal"]
        )
    )


    content.append(Spacer(1,15))


    content.append(
        Paragraph(
            "Tasks",
            styles["Heading2"]
        )
    )


    task_data = [
        [
            "Task",
            "Status"
        ]
    ]


    for task in tasks:

        task_data.append(
            [
                task[2],
                task[3]
            ]
        )


    task_table = Table(task_data)

    task_table.setStyle(
        TableStyle([
            ("GRID",(0,0),(-1,-1),0.5,None)
        ])
    )


    content.append(task_table)

    content.append(Spacer(1,15))


    content.append(
        Paragraph(
            "Documents",
            styles["Heading2"]
        )
    )


    doc_data = [
        [
            "Document",
            "Status"
        ]
    ]


    for item in docs:

        doc_data.append(
            [
                item[2],
                item[3]
            ]
        )


    doc_table = Table(doc_data)

    doc_table.setStyle(
        TableStyle([
            ("GRID",(0,0),(-1,-1),0.5,None)
        ])
    )


    content.append(doc_table)

    content.append(Spacer(1,15))


    info = [
        f"Company: {case[11]}",
        f"Assigned To: {case[12]}",
        f"Created At: {case[13]}",
        f"Workflow State: {case[8]}",
        f"Case History: {case[14]}",
        f"Audit Log: {case[15]}"
    ]


    for item in info:

        content.append(
            Paragraph(
                item,
                styles["Normal"]
            )
        )


    content.append(Spacer(1,20))


    content.append(
        Paragraph(
            "Generated by MobilityFlow AI",
            styles["Italic"]
        )
    )


    doc.build(content)
